INSERT INTO sc_mst.trxtype (kdtrx, jenistrx, uraian) VALUES
    ('AF1','PASSET','APPROVAL SUPERVISOR'),
    ('AF2','PASSET','APPROVAL MANAGER'),
    ('AF3','PASSET','APPROVAL RSM'),
    ('AF4','PASSET','APPROVAL MANAGER KEUANGAN'),
    ('AF5','PASSET','APPROVAL DIREKSI')
ON CONFLICT
    DO NOTHING;